#Kabanero! on activate substitute StackId for text 'StackId'
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: StackId-build-deploy-pl
spec:
  params:
    - name: event-type
      type: string
      description: "The event type"
      default: push
    - name: event-ref
      type: string
      description: "The event ref"
      default: refs/heads/master
    - name: deploy-namespace
      type: string
      description: "The namespace to deploy the app into"
    - name: deploy-image-pull-secret
      description: The image pull secret for the appsody app
    - name: react-project-path
      description: The path to the react project
      default: "."
      type: string
    - name: appsody-project-path
      description: The path to the appsody project
      default: server
      type: string
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: validate-stack-task
      taskRef:
        name: StackId-validate-stack-task
      params:
        - name: appsody-project-path
          value: $(params.appsody-project-path)
      resources:
        inputs:
          - name: git-source
            resource: git-source
    - name: build-push-task
      taskRef:
        name: StackId-build-push-task
      runAfter: [validate-stack-task]
      params:
        - name: react-project-path
          value: $(params.react-project-path)
        - name: appsody-project-path
          value: $(params.appsody-project-path)
        - name: event-ref
          value: $(params.event-ref)
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image
          - name: git-source
            resource: git-source
    - name: image-scan-task
      taskRef:
        name: StackId-image-scan-task
      runAfter: [build-push-task]
      resources:
        inputs:
          - name: git-source
            resource: git-source
            from: [build-push-task]
          - name: docker-image
            resource: docker-image
            from: [build-push-task]
    - name: deploy-task
      conditions:
        - conditionRef: StackId-deployment-condition
          params:
            - name: event-type
              value: $(params.event-type)
            - name: event-ref
              value: $(params.event-ref)
      taskRef:
        name: StackId-deploy-task
      runAfter: [image-scan-task]
      params:
        - name: namespace
          value: $(params.deploy-namespace)
        - name: image-pull-secret
          value: $(params.deploy-image-pull-secret)
      resources:
        inputs:
          - name: git-source
            resource: git-source
            from: [build-push-task]
          - name: docker-image
            resource: docker-image
            from: [build-push-task]
